
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batik
 */
public class DisplayBooks_Page extends javax.swing.JFrame {

    /**
     * Creates new form DisplayBooks_Page
     */
    public DisplayBooks_Page() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
    private int userType;

    public DisplayBooks_Page(int userType) {
    
    this.userType = userType;
    initComponents();
    setLocationRelativeTo(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterabookid_label = new javax.swing.JLabel();
        enterbookid_tf = new javax.swing.JTextField();
        display_button = new javax.swing.JButton();
        BacktoMenu = new javax.swing.JToggleButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DISPLAY BOOK INFORMATION");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        enterabookid_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterabookid_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterabookid_label.setText("ENTER A BOOK ID :");
        enterabookid_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        enterbookid_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterbookid_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbookid_tfActionPerformed(evt);
            }
        });

        display_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        display_button.setText("DISPLAY");
        display_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        display_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_buttonActionPerformed(evt);
            }
        });

        BacktoMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BacktoMenu.setText("BACK TO MENU");
        BacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(enterabookid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(enterbookid_tf)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(display_button, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BacktoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BacktoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterabookid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterbookid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(display_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterbookid_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbookid_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterbookid_tfActionPerformed

    private void display_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_buttonActionPerformed

    String bookIdStr = enterbookid_tf.getText().trim();

    if (bookIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Book ID.");
        return;
    }

    try { 
        int bookId = Integer.parseInt(bookIdStr);
        
      
        DataBase db = new DataBase();
        Book book = db.getBookById(bookId);

        if (book != null) {
            String info = "Title: " + book.getTitle() + "\n"
                        + "Author ID: " + book.getAuthorId() + "\n"
                        + "Year: " + book.getYear() + "\n"
                        + "Pages: " + book.getNumberOfPages() + "\n"
                        + "Cover: " + book.getCover() + "\n"
                        + "About: " + book.getAbout() + "\n"
                        + "Read: " + book.getRead() + "\n"
                        + "Rating: " + book.getRating() + "\n"
                        + "Comments: " + book.getComments() + "\n"
                        + "Release Date: " + (book.getReleaseDate() != null ? book.getReleaseDate().toString() : "N/A");

            JOptionPane.showMessageDialog(this, info);

        } else {
            JOptionPane.showMessageDialog(this, "No book found with ID: " + bookId);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Book ID must be a number.");
    }


        
        
        
        
        
    }//GEN-LAST:event_display_buttonActionPerformed

    private void BacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMenuActionPerformed
     this.setVisible(false);
     return;
    }//GEN-LAST:event_BacktoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBooks_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BacktoMenu;
    private javax.swing.JButton display_button;
    private javax.swing.JLabel enterabookid_label;
    private javax.swing.JTextField enterbookid_tf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
