
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batik
 */
public class EditBook_page extends javax.swing.JFrame {

    private int bookId;
    private int authorId;
    int userType;
    
    public EditBook_page() {
    initComponents(); 
    JOptionPane.showMessageDialog(this, "Please open this form with a Book ID.");
    this.dispose();  }
    
    
    
    public EditBook_page(int userType,int nothing) {   //there is another func with same sign(that takes 1 integer) for 
                                                        //avoiding these i give a additional input that is does nothing
    this.userType = userType;
    initComponents();
    setLocationRelativeTo(null);
    }

    

    

    
    public EditBook_page(Book book) {

    initComponents();
    setLocationRelativeTo(null); 

    
    bookID_tf.setText(String.valueOf(book.getBookId()));
    bookID_tf.setEditable(false); // ID can not be change by design

    title_tf.setText(book.getTitle());
    year_tf.setText(String.valueOf(book.getYear()));
    pages_tf.setText(String.valueOf(book.getNumberOfPages()));
    cover_tf.setText(book.getCover());
    about_tf.setText(book.getAbout());
    read_tf.setText(String.valueOf(book.getRead()));
    rating_tf.setText(String.valueOf(book.getRating()));
    comments_tf.setText(book.getComments());

    if (book.getReleaseDate() != null) {
        releasedate_tf.setText(book.getReleaseDate().toString());
    } else {
        releasedate_tf.setText("");
    }

    authorID_tf.setText(String.valueOf(book.getAuthorId()));
}


    public EditBook_page(int bookId) {
    initComponents();

    DataBase db = new DataBase();
    Book book = db.getBookById(bookId);

    if (book != null) {
        title_tf.setText(book.getTitle());
        year_tf.setText(String.valueOf(book.getYear()));
        pages_tf.setText(String.valueOf(book.getNumberOfPages()));
        cover_tf.setText(book.getCover());
        about_tf.setText(book.getAbout());
        read_tf.setText(String.valueOf(book.getRead()));
        rating_tf.setText(String.valueOf(book.getRating()));
        comments_tf.setText(book.getComments());
        releasedate_tf.setText(book.getReleaseDate() != null ? book.getReleaseDate().toString() : "");
        authorID_tf.setText(String.valueOf(book.getAuthorId()));
    } else {
        JOptionPane.showMessageDialog(this, "No book found with ID: " + bookId);
        this.dispose(); 
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_tf = new javax.swing.JTextField();
        bookid_label = new javax.swing.JLabel();
        bookid_label1 = new javax.swing.JLabel();
        bookid_label2 = new javax.swing.JLabel();
        bookid_label3 = new javax.swing.JLabel();
        bookid_label4 = new javax.swing.JLabel();
        bookid_label5 = new javax.swing.JLabel();
        bookid_label6 = new javax.swing.JLabel();
        bookid_label7 = new javax.swing.JLabel();
        bookid_label8 = new javax.swing.JLabel();
        bookid_label9 = new javax.swing.JLabel();
        pages_tf = new javax.swing.JTextField();
        about_tf = new javax.swing.JTextField();
        read_tf = new javax.swing.JTextField();
        cover_tf = new javax.swing.JTextField();
        releasedate_tf = new javax.swing.JTextField();
        comments_tf = new javax.swing.JTextField();
        rating_tf = new javax.swing.JTextField();
        year_tf = new javax.swing.JTextField();
        authorID_tf = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        bookid_label10 = new javax.swing.JLabel();
        bookID_tf = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_tfActionPerformed(evt);
            }
        });

        bookid_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label.setText("COVER :");
        bookid_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label1.setText("TITLE :");
        bookid_label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label2.setText("PAGES :");
        bookid_label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label3.setText("YEAR :");
        bookid_label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label4.setText("READ :");
        bookid_label4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label5.setText("ABOUT :");
        bookid_label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label6.setText("COMMENTS :");
        bookid_label6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label7.setText("AUTHOR ID :");
        bookid_label7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label8.setText("RATING :");
        bookid_label8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_label9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label9.setText("RELEASE DATE :");
        bookid_label9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pages_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pages_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pages_tfActionPerformed(evt);
            }
        });

        about_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        about_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_tfActionPerformed(evt);
            }
        });

        read_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        read_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_tfActionPerformed(evt);
            }
        });

        cover_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cover_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cover_tfActionPerformed(evt);
            }
        });

        releasedate_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        releasedate_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releasedate_tfActionPerformed(evt);
            }
        });

        comments_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        comments_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comments_tfActionPerformed(evt);
            }
        });

        rating_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rating_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rating_tfActionPerformed(evt);
            }
        });

        year_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        year_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_tfActionPerformed(evt);
            }
        });

        authorID_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        authorID_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorID_tfActionPerformed(evt);
            }
        });

        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        bookid_label10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label10.setText("BOOK ID :");
        bookid_label10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookID_tf.setEditable(false);
        bookID_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookID_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID_tfActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BACK TO MAIN MENU");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookid_label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookid_label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bookid_label9))
                    .addComponent(bookid_label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rating_tf)
                    .addComponent(cover_tf)
                    .addComponent(about_tf)
                    .addComponent(read_tf)
                    .addComponent(title_tf)
                    .addComponent(year_tf)
                    .addComponent(pages_tf)
                    .addComponent(releasedate_tf)
                    .addComponent(authorID_tf)
                    .addComponent(comments_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(bookID_tf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookid_label10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pages_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cover_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(about_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rating_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookid_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comments_tf))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(releasedate_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookid_label9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookid_label7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void title_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_tfActionPerformed

    private void pages_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pages_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pages_tfActionPerformed

    private void about_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_about_tfActionPerformed

    private void read_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read_tfActionPerformed

    private void cover_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cover_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cover_tfActionPerformed

    private void releasedate_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releasedate_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_releasedate_tfActionPerformed

    private void comments_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comments_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comments_tfActionPerformed

    private void rating_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rating_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rating_tfActionPerformed

    private void year_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_tfActionPerformed

    private void authorID_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorID_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorID_tfActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
    
    try {
        
        int bookId = Integer.parseInt(bookID_tf.getText().trim());
        String title = title_tf.getText().trim();
        int year = Integer.parseInt(year_tf.getText().trim());
        int pages = Integer.parseInt(pages_tf.getText().trim());
        String cover = cover_tf.getText().trim();
        String about = about_tf.getText().trim();
        int read = Integer.parseInt(read_tf.getText().trim());
        int rating = Integer.parseInt(rating_tf.getText().trim());
        String comments = comments_tf.getText().trim();
        String releaseDate = releasedate_tf.getText().trim();
        int authorId = Integer.parseInt(authorID_tf.getText().trim());

        // database update
        DataBase db = new DataBase();
        boolean success = db.updateBook(bookId, title, year, pages, cover, about, read, rating, comments, releaseDate, authorId);

        if (success) {
            JOptionPane.showMessageDialog(this, "Book updated successfully!");
            this.dispose(); 
            new GUI().setVisible(true);// pencereyi kapat
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update book.");
        }

         } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }



    }//GEN-LAST:event_update_buttonActionPerformed

    private void bookID_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookID_tfActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    
        new GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBook_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBook_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBook_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBook_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField about_tf;
    private javax.swing.JTextField authorID_tf;
    private javax.swing.JTextField bookID_tf;
    private javax.swing.JLabel bookid_label;
    private javax.swing.JLabel bookid_label1;
    private javax.swing.JLabel bookid_label10;
    private javax.swing.JLabel bookid_label2;
    private javax.swing.JLabel bookid_label3;
    private javax.swing.JLabel bookid_label4;
    private javax.swing.JLabel bookid_label5;
    private javax.swing.JLabel bookid_label6;
    private javax.swing.JLabel bookid_label7;
    private javax.swing.JLabel bookid_label8;
    private javax.swing.JLabel bookid_label9;
    private javax.swing.JTextField comments_tf;
    private javax.swing.JTextField cover_tf;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField pages_tf;
    private javax.swing.JTextField rating_tf;
    private javax.swing.JTextField read_tf;
    private javax.swing.JTextField releasedate_tf;
    private javax.swing.JTextField title_tf;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField year_tf;
    // End of variables declaration//GEN-END:variables
}
