

import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batik
 */
public class GUI extends javax.swing.JFrame {
    
    int userType;
    private User currentUser;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
    public GUI(User user) {
        initComponents();
        this.currentUser = user;

        userType = currentUser.getUserType(); 
        System.out.println("User type is: " + userType);
    }
    

    


   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayundreadbooks_button = new javax.swing.JButton();
        addbook_button = new javax.swing.JButton();
        removebook_button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchauthorbyname_button = new javax.swing.JButton();
        display_book_info_button = new javax.swing.JButton();
        Logout_button = new javax.swing.JButton();
        updatebook_button = new javax.swing.JButton();
        displayfavouritebooks_button = new javax.swing.JButton();
        displayfavouriteAuthors_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        displayundreadbooks_button.setText("DISPLAY UNREADED BOOKS");
        displayundreadbooks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayundreadbooks_buttonActionPerformed(evt);
            }
        });

        addbook_button.setText("ADD BOOK");
        addbook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbook_buttonActionPerformed(evt);
            }
        });

        removebook_button.setText("REMOVE BOOK");
        removebook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebook_buttonActionPerformed(evt);
            }
        });

        jButton4.setText("DISPLAY  BOOK'S COVER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        searchauthorbyname_button.setText("SEARCH AUTHOR BY NAME");
        searchauthorbyname_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchauthorbyname_buttonActionPerformed(evt);
            }
        });

        display_book_info_button.setText("DISPLAY BOOK INFO");
        display_book_info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_book_info_buttonActionPerformed(evt);
            }
        });

        Logout_button.setText("Logout");
        Logout_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        updatebook_button.setText("UPDATE BOOK");
        updatebook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebook_buttonActionPerformed(evt);
            }
        });

        displayfavouritebooks_button.setText("DISPLAY FAVORITE BOOKS");
        displayfavouritebooks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayfavouritebooks_buttonActionPerformed(evt);
            }
        });

        displayfavouriteAuthors_button.setText("DISPLAY FAVORITE AUTHORS");
        displayfavouriteAuthors_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayfavouriteAuthors_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN PAGE");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchauthorbyname_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addbook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removebook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayfavouriteAuthors_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayundreadbooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(display_book_info_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updatebook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayfavouritebooks_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display_book_info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removebook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatebook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchauthorbyname_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayfavouritebooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayfavouriteAuthors_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayundreadbooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        dispose();
        new LoginPage().setVisible(true);  
        this.setVisible(false); 

    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void display_book_info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_book_info_buttonActionPerformed
        new DisplayBooks_Page(userType).setVisible(true);
       
    }//GEN-LAST:event_display_book_info_buttonActionPerformed

    private void displayfavouritebooks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayfavouritebooks_buttonActionPerformed
      DataBase db = new DataBase();
    List<Book> favoriteBooks = db.getFavoriteBooks();

    if (favoriteBooks.isEmpty()) {
    JOptionPane.showMessageDialog(null, "There are no favorite books.");
    } else {
    new FavouriteBooks_Page(favoriteBooks).setVisible(true);
    }


    }//GEN-LAST:event_displayfavouritebooks_buttonActionPerformed

    private void displayfavouriteAuthors_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayfavouriteAuthors_buttonActionPerformed
  
    DataBase db = new DataBase();
    List<Author> authors = db.getFavoriteAuthors();
    FavoriteAuthors_Page page = new FavoriteAuthors_Page(authors);
    page.setVisible(true);

    }//GEN-LAST:event_displayfavouriteAuthors_buttonActionPerformed

    
    private void displayundreadbooks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayundreadbooks_buttonActionPerformed
    DataBase db = new DataBase();
    List<Book> unreadBooks = db.getUnreadBooks();

    if (unreadBooks.isEmpty()) {
    JOptionPane.showMessageDialog(null, "There are no unread books.");
    } else {
    new UnreadBooksPage(unreadBooks).setVisible(true);
    }


    }//GEN-LAST:event_displayundreadbooks_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    new DisplayBookCoverage(userType).setVisible(true);
    

    }//GEN-LAST:event_jButton4ActionPerformed

    private void addbook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbook_buttonActionPerformed
        new AddBook_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addbook_buttonActionPerformed

    private void removebook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebook_buttonActionPerformed
        new RemoveBookPage(userType).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removebook_buttonActionPerformed

    private void updatebook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebook_buttonActionPerformed
        new UpdateBook(userType).setVisible(true);
        this.setVisible(false);
     
    }//GEN-LAST:event_updatebook_buttonActionPerformed

    private void searchauthorbyname_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchauthorbyname_buttonActionPerformed
       new SearchAnAuthorByName(userType).setVisible(true);
       
    }//GEN-LAST:event_searchauthorbyname_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout_button;
    private javax.swing.JButton addbook_button;
    private javax.swing.JButton display_book_info_button;
    private javax.swing.JButton displayfavouriteAuthors_button;
    private javax.swing.JButton displayfavouritebooks_button;
    private javax.swing.JButton displayundreadbooks_button;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton removebook_button;
    private javax.swing.JButton searchauthorbyname_button;
    private javax.swing.JButton updatebook_button;
    // End of variables declaration//GEN-END:variables
}
