
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batik
 */
public class RemoveBookPage extends javax.swing.JFrame {

    /**
     * Creates new form RemoveBookPage
     */
    public RemoveBookPage() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
    private int userType;

    public RemoveBookPage(int userType) {
    this.userType = userType;
    initComponents();
    setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        deletebook_button = new javax.swing.JButton();
        bookid_label = new javax.swing.JLabel();
        bookid_textf = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DELETE BOOK");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        deletebook_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deletebook_button.setText("DELETE BOOK");
        deletebook_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletebook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebook_buttonActionPerformed(evt);
            }
        });

        bookid_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookid_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookid_label.setText("BOOK ID :");
        bookid_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bookid_textf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookid_textf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookid_textfActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BACK TO MAIN MENU");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletebook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bookid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(bookid_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookid_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deletebook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebook_buttonActionPerformed

    String idStr = bookid_textf.getText().trim(); //Book ID check

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Book ID.");
        return;
    }

    try {
        int bookId = Integer.parseInt(idStr);
        DataBase db = new DataBase();
        boolean removed = db.removeBookById(bookId);

        if (removed) {
            JOptionPane.showMessageDialog(this, "Book removed successfully!");
            this.dispose();
            new GUI().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No book found with ID: " + bookId);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Book ID must be a number.");
    }

        
        
    }//GEN-LAST:event_deletebook_buttonActionPerformed

    private void bookid_textfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookid_textfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookid_textfActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      
        new GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveBookPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookid_label;
    private javax.swing.JTextField bookid_textf;
    private javax.swing.JButton deletebook_button;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
