
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batik
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
         setLocationRelativeTo(null); 
    }
    
    private int userType;

    public UserFrame(int userType) {
    initComponents();
    this.userType=userType;
    setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout_button = new javax.swing.JButton();
        display_book_info_button = new javax.swing.JButton();
        displayBooksCover_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        displayfavouritebooks_button = new javax.swing.JButton();
        displayfavouriteAuthors_button = new javax.swing.JButton();
        displayundreadbooks_button = new javax.swing.JButton();
        searchauthorbyname_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logout_button.setText("Logout");
        Logout_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        display_book_info_button.setText("DISPLAY BOOK INFO");
        display_book_info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_book_info_buttonActionPerformed(evt);
            }
        });

        displayBooksCover_button.setText("DISPLAY  BOOK'S COVER");
        displayBooksCover_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBooksCover_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PLEASE SELECT");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WELCOME THE LIBRARY");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        displayfavouritebooks_button.setText("DISPLAY FAVORITE BOOKS");
        displayfavouritebooks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayfavouritebooks_buttonActionPerformed(evt);
            }
        });

        displayfavouriteAuthors_button.setText("DISPLAY FAVORITE AUTHORS");
        displayfavouriteAuthors_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayfavouriteAuthors_buttonActionPerformed(evt);
            }
        });

        displayundreadbooks_button.setText("DISPLAY UNREADED BOOKS");
        displayundreadbooks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayundreadbooks_buttonActionPerformed(evt);
            }
        });

        searchauthorbyname_button1.setText("SEARCH AUTHOR BY NAME");
        searchauthorbyname_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchauthorbyname_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayfavouritebooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayundreadbooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchauthorbyname_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayBooksCover_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(display_book_info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayfavouriteAuthors_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display_book_info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchauthorbyname_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayfavouritebooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayfavouriteAuthors_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBooksCover_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayundreadbooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        dispose();  
        new LoginPage().setVisible(true); 
        this.setVisible(false); 
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void display_book_info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_book_info_buttonActionPerformed
       new DisplayBooks_Page(userType).setVisible(true);
      
    }//GEN-LAST:event_display_book_info_buttonActionPerformed

    private void displayBooksCover_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBooksCover_buttonActionPerformed

         new DisplayBookCoverage(userType).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_displayBooksCover_buttonActionPerformed

    private void displayfavouritebooks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayfavouritebooks_buttonActionPerformed
        DataBase db = new DataBase();
        List<Book> favoriteBooks = db.getFavoriteBooks();

        if (favoriteBooks.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no favorite books.");
        } else {
            new FavouriteBooks_Page(favoriteBooks).setVisible(true);
        }

    }//GEN-LAST:event_displayfavouritebooks_buttonActionPerformed

    private void displayfavouriteAuthors_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayfavouriteAuthors_buttonActionPerformed

        DataBase db = new DataBase();
        List<Author> authors = db.getFavoriteAuthors();
        FavoriteAuthors_Page page = new FavoriteAuthors_Page(authors);
        page.setVisible(true);
    }//GEN-LAST:event_displayfavouriteAuthors_buttonActionPerformed

    private void displayundreadbooks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayundreadbooks_buttonActionPerformed
        DataBase db = new DataBase();
        List<Book> unreadBooks = db.getUnreadBooks();

        if (unreadBooks.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no unread books.");
        } else {
            new UnreadBooksPage(unreadBooks).setVisible(true);
        }

    }//GEN-LAST:event_displayundreadbooks_buttonActionPerformed

    private void searchauthorbyname_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchauthorbyname_button1ActionPerformed
        new SearchAnAuthorByName(userType).setVisible(true);

    }//GEN-LAST:event_searchauthorbyname_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout_button;
    private javax.swing.JButton displayBooksCover_button;
    private javax.swing.JButton display_book_info_button;
    private javax.swing.JButton displayfavouriteAuthors_button;
    private javax.swing.JButton displayfavouritebooks_button;
    private javax.swing.JButton displayundreadbooks_button;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton searchauthorbyname_button1;
    // End of variables declaration//GEN-END:variables
}
